In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df=pd.read_excel("shipwreckdatabase.xlsx")
df

,Wreck Name,Classification,Place of Loss,Date of Loss,Description,Unnamed: 5,Unnamed: 6
0,Actur,Schooner,"Carlingford Bar to Greencastle pier, Carlingfo...",28/12/1894,"Schooner of Dublin, stranded en route to Cunni...",NaN,NaN
1,Anne McLeod,Schooner,"Carlingford, near, Carlingford Lough",22/01/1862,"71-ton, 6-year-old schooner. Captain was Darby...",NaN,NaN
2,Barbara & Jannette,Sloop,"Carlingford Bar, outside, on a rock, Carlingfo...",18/02/1824,"Sloop en route from Irvine to Dundalk, struck ...",NaN,NaN
3,Bee (SS),Iron Steamship,Carlingford Lough entrance/ Helly Hunter Rock,19/10/1888,"88-ton, 18-year-old iron steamship. Owned by ‘...",NaN,NaN
4,Bloom,Schooner,"Carlingford Bar, Carlingford Lough",23/10/1838,"Schooner valued at £600, became a total wreck,...",NaN,NaN
...,...,...,...,...,...,...,...
28229,Sovereign of the Seas,Clipper,Pyramid Shoal.,6 August 1859,A clipper that was wrecked on the Pyramid Shoal.,NaN,NaN
28230,Takao,heavy cruiser,NaN,1946-10-19 00:00:00,A Takao-class heavy cruiser that was surrender...,NaN,NaN
28231,U-181,U-Boat,Port Klang,1946-02-12 00:00:00,A Type IXD2 U-boat that was scuttled near Port...,NaN,NaN
28232,U-859,U-Boat,NaN,1944-09-23 00:00:00,A Type IXD2 U-boat that was sunk by HMSÂ Trenc...,NaN,NaN
28233,U-862,U-Boat,Port Klang,1946-02-13 00:00:00,A Type IXD2 U-boat that was scuttled near Port...,NaN,NaN

In [4]:
df = df.drop(columns=['Unnamed: 5', 'Unnamed: 6'])

In [5]:
df

,Wreck Name,Classification,Place of Loss,Date of Loss,Description
0,Actur,Schooner,"Carlingford Bar to Greencastle pier, Carlingfo...",28/12/1894,"Schooner of Dublin, stranded en route to Cunni..."
1,Anne McLeod,Schooner,"Carlingford, near, Carlingford Lough",22/01/1862,"71-ton, 6-year-old schooner. Captain was Darby..."
2,Barbara & Jannette,Sloop,"Carlingford Bar, outside, on a rock, Carlingfo...",18/02/1824,"Sloop en route from Irvine to Dundalk, struck ..."
3,Bee (SS),Iron Steamship,Carlingford Lough entrance/ Helly Hunter Rock,19/10/1888,"88-ton, 18-year-old iron steamship. Owned by ‘..."
4,Bloom,Schooner,"Carlingford Bar, Carlingford Lough",23/10/1838,"Schooner valued at £600, became a total wreck,..."
...,...,...,...,...,...
28229,Sovereign of the Seas,Clipper,Pyramid Shoal.,6 August 1859,A clipper that was wrecked on the Pyramid Shoal.
28230,Takao,heavy cruiser,NaN,1946-10-19 00:00:00,A Takao-class heavy cruiser that was surrender...
28231,U-181,U-Boat,Port Klang,1946-02-12 00:00:00,A Type IXD2 U-boat that was scuttled near Port...
28232,U-859,U-Boat,NaN,1944-09-23 00:00:00,A Type IXD2 U-boat that was sunk by HMSÂ Trenc...
28233,U-862,U-Boat,Port Klang,1946-02-13 00:00:00,A Type IXD2 U-boat that was scuttled near Port...

In [6]:
df.isnull().sum()

Wreck Name          18
Classification    7811
Place of Loss     4046
Date of Loss       423
Description         79
dtype: int64

In [7]:
df.dropna()

,Wreck Name,Classification,Place of Loss,Date of Loss,Description
0,Actur,Schooner,"Carlingford Bar to Greencastle pier, Carlingfo...",28/12/1894,"Schooner of Dublin, stranded en route to Cunni..."
1,Anne McLeod,Schooner,"Carlingford, near, Carlingford Lough",22/01/1862,"71-ton, 6-year-old schooner. Captain was Darby..."
2,Barbara & Jannette,Sloop,"Carlingford Bar, outside, on a rock, Carlingfo...",18/02/1824,"Sloop en route from Irvine to Dundalk, struck ..."
3,Bee (SS),Iron Steamship,Carlingford Lough entrance/ Helly Hunter Rock,19/10/1888,"88-ton, 18-year-old iron steamship. Owned by ‘..."
4,Bloom,Schooner,"Carlingford Bar, Carlingford Lough",23/10/1838,"Schooner valued at £600, became a total wreck,..."
...,...,...,...,...,...
28227,Mousquet,destroyer,Penang,2014-10-28 00:00:00,An Arquebuse-class destroyer sunk by the Imper...
28228,MyÅkÅ,cruiser,Port Klang,1946-06-08 00:00:00,A MyÅkÅ-class cruiser that was scuttled near...
28229,Sovereign of the Seas,Clipper,Pyramid Shoal.,6 August 1859,A clipper that was wrecked on the Pyramid Shoal.
28231,U-181,U-Boat,Port Klang,1946-02-12 00:00:00,A Type IXD2 U-boat that was scuttled near Port...
28233,U-862,U-Boat,Port Klang,1946-02-13 00:00:00,A Type IXD2 U-boat that was scuttled near Port...

In [8]:
df=df.fillna("Unknown")
df

,Wreck Name,Classification,Place of Loss,Date of Loss,Description
0,Actur,Schooner,"Carlingford Bar to Greencastle pier, Carlingfo...",28/12/1894,"Schooner of Dublin, stranded en route to Cunni..."
1,Anne McLeod,Schooner,"Carlingford, near, Carlingford Lough",22/01/1862,"71-ton, 6-year-old schooner. Captain was Darby..."
2,Barbara & Jannette,Sloop,"Carlingford Bar, outside, on a rock, Carlingfo...",18/02/1824,"Sloop en route from Irvine to Dundalk, struck ..."
3,Bee (SS),Iron Steamship,Carlingford Lough entrance/ Helly Hunter Rock,19/10/1888,"88-ton, 18-year-old iron steamship. Owned by ‘..."
4,Bloom,Schooner,"Carlingford Bar, Carlingford Lough",23/10/1838,"Schooner valued at £600, became a total wreck,..."
...,...,...,...,...,...
28229,Sovereign of the Seas,Clipper,Pyramid Shoal.,6 August 1859,A clipper that was wrecked on the Pyramid Shoal.
28230,Takao,heavy cruiser,Unknown,1946-10-19 00:00:00,A Takao-class heavy cruiser that was surrender...
28231,U-181,U-Boat,Port Klang,1946-02-12 00:00:00,A Type IXD2 U-boat that was scuttled near Port...
28232,U-859,U-Boat,Unknown,1944-09-23 00:00:00,A Type IXD2 U-boat that was sunk by HMSÂ Trenc...
28233,U-862,U-Boat,Port Klang,1946-02-13 00:00:00,A Type IXD2 U-boat that was scuttled near Port...

In [9]:
df=df.drop_duplicates()
df

,Wreck Name,Classification,Place of Loss,Date of Loss,Description
0,Actur,Schooner,"Carlingford Bar to Greencastle pier, Carlingfo...",28/12/1894,"Schooner of Dublin, stranded en route to Cunni..."
1,Anne McLeod,Schooner,"Carlingford, near, Carlingford Lough",22/01/1862,"71-ton, 6-year-old schooner. Captain was Darby..."
2,Barbara & Jannette,Sloop,"Carlingford Bar, outside, on a rock, Carlingfo...",18/02/1824,"Sloop en route from Irvine to Dundalk, struck ..."
3,Bee (SS),Iron Steamship,Carlingford Lough entrance/ Helly Hunter Rock,19/10/1888,"88-ton, 18-year-old iron steamship. Owned by ‘..."
4,Bloom,Schooner,"Carlingford Bar, Carlingford Lough",23/10/1838,"Schooner valued at £600, became a total wreck,..."
...,...,...,...,...,...
28229,Sovereign of the Seas,Clipper,Pyramid Shoal.,6 August 1859,A clipper that was wrecked on the Pyramid Shoal.
28230,Takao,heavy cruiser,Unknown,1946-10-19 00:00:00,A Takao-class heavy cruiser that was surrender...
28231,U-181,U-Boat,Port Klang,1946-02-12 00:00:00,A Type IXD2 U-boat that was scuttled near Port...
28232,U-859,U-Boat,Unknown,1944-09-23 00:00:00,A Type IXD2 U-boat that was sunk by HMSÂ Trenc...
28233,U-862,U-Boat,Port Klang,1946-02-13 00:00:00,A Type IXD2 U-boat that was scuttled near Port...