In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_excel("shipwreckdatabase.xlsx")
df

,Wreck Name,Classification,Place of Loss,Date of Loss,Description,Unnamed: 5,Unnamed: 6
0,Actur,Schooner,"Carlingford Bar to Greencastle pier, Carlingfo...",28/12/1894,"Schooner of Dublin, stranded en route to Cunni...",NaN,NaN
1,Anne McLeod,Schooner,"Carlingford, near, Carlingford Lough",22/01/1862,"71-ton, 6-year-old schooner. Captain was Darby...",NaN,NaN
2,Barbara & Jannette,Sloop,"Carlingford Bar, outside, on a rock, Carlingfo...",18/02/1824,"Sloop en route from Irvine to Dundalk, struck ...",NaN,NaN
3,Bee (SS),Iron Steamship,Carlingford Lough entrance/ Helly Hunter Rock,19/10/1888,"88-ton, 18-year-old iron steamship. Owned by ‘...",NaN,NaN
4,Bloom,Schooner,"Carlingford Bar, Carlingford Lough",23/10/1838,"Schooner valued at £600, became a total wreck,...",NaN,NaN
...,...,...,...,...,...,...,...
28229,Sovereign of the Seas,Clipper,Pyramid Shoal.,6 August 1859,A clipper that was wrecked on the Pyramid Shoal.,NaN,NaN
28230,Takao,heavy cruiser,NaN,1946-10-19 00:00:00,A Takao-class heavy cruiser that was surrender...,NaN,NaN
28231,U-181,U-Boat,Port Klang,1946-02-12 00:00:00,A Type IXD2 U-boat that was scuttled near Port...,NaN,NaN
28232,U-859,U-Boat,NaN,1944-09-23 00:00:00,A Type IXD2 U-boat that was sunk by HMSÂ Trenc...,NaN,NaN
28233,U-862,U-Boat,Port Klang,1946-02-13 00:00:00,A Type IXD2 U-boat that was scuttled near Port...,NaN,NaN

In [3]:
df = df.drop(columns=['Unnamed: 5', 'Unnamed: 6'])

In [4]:
df

,Wreck Name,Classification,Place of Loss,Date of Loss,Description
0,Actur,Schooner,"Carlingford Bar to Greencastle pier, Carlingfo...",28/12/1894,"Schooner of Dublin, stranded en route to Cunni..."
1,Anne McLeod,Schooner,"Carlingford, near, Carlingford Lough",22/01/1862,"71-ton, 6-year-old schooner. Captain was Darby..."
2,Barbara & Jannette,Sloop,"Carlingford Bar, outside, on a rock, Carlingfo...",18/02/1824,"Sloop en route from Irvine to Dundalk, struck ..."
3,Bee (SS),Iron Steamship,Carlingford Lough entrance/ Helly Hunter Rock,19/10/1888,"88-ton, 18-year-old iron steamship. Owned by ‘..."
4,Bloom,Schooner,"Carlingford Bar, Carlingford Lough",23/10/1838,"Schooner valued at £600, became a total wreck,..."
...,...,...,...,...,...
28229,Sovereign of the Seas,Clipper,Pyramid Shoal.,6 August 1859,A clipper that was wrecked on the Pyramid Shoal.
28230,Takao,heavy cruiser,NaN,1946-10-19 00:00:00,A Takao-class heavy cruiser that was surrender...
28231,U-181,U-Boat,Port Klang,1946-02-12 00:00:00,A Type IXD2 U-boat that was scuttled near Port...
28232,U-859,U-Boat,NaN,1944-09-23 00:00:00,A Type IXD2 U-boat that was sunk by HMSÂ Trenc...
28233,U-862,U-Boat,Port Klang,1946-02-13 00:00:00,A Type IXD2 U-boat that was scuttled near Port...

In [5]:
df.isnull().sum()

Wreck Name          18
Classification    7811
Place of Loss     4046
Date of Loss       423
Description         79
dtype: int64

In [6]:
df=df.fillna("Unknown")
df

,Wreck Name,Classification,Place of Loss,Date of Loss,Description
0,Actur,Schooner,"Carlingford Bar to Greencastle pier, Carlingfo...",28/12/1894,"Schooner of Dublin, stranded en route to Cunni..."
1,Anne McLeod,Schooner,"Carlingford, near, Carlingford Lough",22/01/1862,"71-ton, 6-year-old schooner. Captain was Darby..."
2,Barbara & Jannette,Sloop,"Carlingford Bar, outside, on a rock, Carlingfo...",18/02/1824,"Sloop en route from Irvine to Dundalk, struck ..."
3,Bee (SS),Iron Steamship,Carlingford Lough entrance/ Helly Hunter Rock,19/10/1888,"88-ton, 18-year-old iron steamship. Owned by ‘..."
4,Bloom,Schooner,"Carlingford Bar, Carlingford Lough",23/10/1838,"Schooner valued at £600, became a total wreck,..."
...,...,...,...,...,...
28229,Sovereign of the Seas,Clipper,Pyramid Shoal.,6 August 1859,A clipper that was wrecked on the Pyramid Shoal.
28230,Takao,heavy cruiser,Unknown,1946-10-19 00:00:00,A Takao-class heavy cruiser that was surrender...
28231,U-181,U-Boat,Port Klang,1946-02-12 00:00:00,A Type IXD2 U-boat that was scuttled near Port...
28232,U-859,U-Boat,Unknown,1944-09-23 00:00:00,A Type IXD2 U-boat that was sunk by HMSÂ Trenc...
28233,U-862,U-Boat,Port Klang,1946-02-13 00:00:00,A Type IXD2 U-boat that was scuttled near Port...

In [7]:
df=df.drop_duplicates()
df

,Wreck Name,Classification,Place of Loss,Date of Loss,Description
0,Actur,Schooner,"Carlingford Bar to Greencastle pier, Carlingfo...",28/12/1894,"Schooner of Dublin, stranded en route to Cunni..."
1,Anne McLeod,Schooner,"Carlingford, near, Carlingford Lough",22/01/1862,"71-ton, 6-year-old schooner. Captain was Darby..."
2,Barbara & Jannette,Sloop,"Carlingford Bar, outside, on a rock, Carlingfo...",18/02/1824,"Sloop en route from Irvine to Dundalk, struck ..."
3,Bee (SS),Iron Steamship,Carlingford Lough entrance/ Helly Hunter Rock,19/10/1888,"88-ton, 18-year-old iron steamship. Owned by ‘..."
4,Bloom,Schooner,"Carlingford Bar, Carlingford Lough",23/10/1838,"Schooner valued at £600, became a total wreck,..."
...,...,...,...,...,...
28229,Sovereign of the Seas,Clipper,Pyramid Shoal.,6 August 1859,A clipper that was wrecked on the Pyramid Shoal.
28230,Takao,heavy cruiser,Unknown,1946-10-19 00:00:00,A Takao-class heavy cruiser that was surrender...
28231,U-181,U-Boat,Port Klang,1946-02-12 00:00:00,A Type IXD2 U-boat that was scuttled near Port...
28232,U-859,U-Boat,Unknown,1944-09-23 00:00:00,A Type IXD2 U-boat that was sunk by HMSÂ Trenc...
28233,U-862,U-Boat,Port Klang,1946-02-13 00:00:00,A Type IXD2 U-boat that was scuttled near Port...

In [10]:
# Ensure description is string
df['Description'] = df['Description'].astype(str)
print(f"Dataset shape: {df.shape}")

Dataset shape: (26769, 5)

C:\Users\spectrum\AppData\Local\Temp\ipykernel_17392\2258767409.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Description'] = df['Description'].astype(str)

In [17]:
print("Classification labels:", df['Classification'].unique())

Classification labels: ['Schooner' 'Sloop' 'Iron Steamship' 'Brig' 'Unknown' 'Lugger' 'Snow'
 'Steamship' 'Smack' 'Yawl' 'Steel Steamship' 'Cutter' 'Ketch'
 'Brigantine' 'Lighter' 'Barque' 'Yacht' 'Ship' 'Fishing boat'
 'Crane Vessel' 'Tender' 'Barquentine' 'Collier' 'Dutch Galliot'
 'Screw Steamer' 'Flat' 'Bark' 'Boat' 'Trader' 'Carvel' 'Lugsail'
 'Galliot' 'Dandy' 'Clinker' 'Iron Paddle Steam Tug' 'Sailing Ship'
 'Merchant Vessel' 'Pleasure Boat' 'Trawler' 'Pilot boat' 'Barge'
 'Admiralty/ Decoy Ship' 'Steam Trawler' 'Submarine' 'Sailing Boat'
 'Paddler Steamer' 'Motor Boat' 'Packet boat' 'Wherry' 'Coaster' 'Clipper'
 'Cruiser' 'Vessel' 'Iron Steam Yacht' 'Smack Yacht' 'Hacker' 'Jigger'
 'Tug' 'Wooden Steam Tug' 'Frigate' 'Hobble' 'Steam Tug' 'Stone hacker'
 'Gabbard' 'West Indiaman' 'Skiff' "Man O' War" 'Anti-submarine Drifter'
 'Light Ship' 'Steam Drifter' 'Fishing drifter' 'Lifeboat'
 'Coast Guard Cruiser' 'Iron steam tug' 'Motor Fishing Vessel'
 'Steam Packet' 'Hulk' 'Ironclad Battleship' 'Scow' 'Steam Yacht' 'Nobby'
 'Auxiliary Vessel' 'Ferry' 'Full-rigged ship' 'Tanker' 'Gabarts'
 'Steam Liner' 'Dredger' 'Battleship' 'Polacca' 'Motor schooner'
 'Market boat' 'River Steamer' 'Liner' 'Royal Ship' 'Motor-ship'
 'Privateer' 'Mine-sweeper' 'Transport' 'Hooker' 'Corvette' 'Hopper Barge'
 'Whale Boat' 'Destroyer' 'Canoe' 'Row boat' 'Logboat' 'Zabra' 'Galleon'
 'Screw Gunboat' 'Longboat' 'Urca' 'Glothogue' 'Mail boat' 'Pookaun'
 'Spritsail' 'Curragh' 'Nao' 'Mule' 'East Indiaman' 'Pinnace' 'Galley'
 'Dreadnought' 'Steam launch' 'Tank-landing craft' 'Cargo Ship' 'Zulu'
 'Airplane' 'Pink' 'Flyboat' 'Aircraft Carrier' 'Water Wag' 'Fireship'
 'Other' 'Motor Trawler' 'Punt' 'Cot' 'Steam dredger' 'vessel'
 'passenger ship' 'cargo ship' 'Russian passenger' 'ocean liner '
 'troop transport' 'ferry' 'battleship' 'aircraft carrier' 'schooner'
 'galleon' 'junk' 'carrack' 'cruiser' 'battlecruiser'
 'submarine support vessel' 'ship of the line' 'tanker' 'sailing ship'
 'escort vessel' 'destroyer' 'frigate' 'fully rigged ship' 'flute ship'
 'fishing ship' 'monitor' 'clipper' 'dredger' 'minesweeper' 'canal boat'
 'minelayer' 'east indiaman' 'corvette' 'barge' 'submarine chaser'
 'patrol boat' 'ironclad' 'barque' 'brig' 'drifter' 'brigantine'
 'landing ship tank' 'gunboat' 'sloop' 'vacht' 'canoe' 'lugger'
 'Sailing ship' 'sealing ship' 'destroyer escort' 'river gunboat'
 'oil platform' 'tug' 'aircraft support vessel' 'torpedo boat' 'submarine'
 'trawler' 'oil tanker' 'Cruise ship' 'U-Boat' 'light cruiser' 'galley'
 ' Roebuck-class fifth' 'troopship' 'passenger liner' 'merchant ship'
 'warship' 'refrigerator ship' 'freighter' 'carrier' 'cruise liner'
 'class ship' 'slave ship' 'convict ship' 'supply ship' 'P&O ship'
 'steamboat' 'Perim' 'cruiseship' 'supply vessel' 'boat' 'Dhow'
 'heavy cruiser' 'transport ship' 'hellship' 'patrol ship' 'Ottoman'
 'Tour boat' 'passenger boat ' 'merchant vessel' 'seaplane tender'
 'hospital ship' 'yacht' 'lumber transport' 'icebreaker' 'French liner'
 'trading ship' 'french ship' 'streamer' 'steam liner' 'tugboat'
 'training ship' 'Vorpostenboot' 'weather ship' 'container ship'
 'paddle streamer' 'steamer' 'cutter' 'ammunation ship' 'mail ship'
 'attack transport' 'liberty ship' 'ketch' 'steamship' 'launch'
 'Dutch ship' 'whaler' 'merchantman' 'lighter' 'defence vessel'
 'depot ship' 'small coaster' 'motor vessel' 'floating crane' 'fleet ship'
 'coal hulk' 'auxiliary ship' 'bulk carrier' 'iron ship' 'cruiser '
 'armoured cruiser' 'Sloop-of-war' 'cruiser sunk' 'turret ship' 'Wexford'
 'coast guard' 'merchant cruiser' 'merchant raider' 'Aviso' 'cargo liner'
 'cargoship' 'merchant streamer' 'oiler']

In [19]:
df.dropna(subset=['Description'], inplace=True)
print(df[['Wreck Name','Classification', 'Place of Loss', 'Date of Loss', 'Description']].head())

           Wreck Name  Classification  \
0               Actur        Schooner
1         Anne McLeod        Schooner
2  Barbara & Jannette           Sloop
3            Bee (SS)  Iron Steamship
4               Bloom        Schooner

                                       Place of Loss Date of Loss  \
0  Carlingford Bar to Greencastle pier, Carlingfo...   28/12/1894
1               Carlingford, near, Carlingford Lough   22/01/1862
2  Carlingford Bar, outside, on a rock, Carlingfo...   18/02/1824
3      Carlingford Lough entrance/ Helly Hunter Rock   19/10/1888
4                 Carlingford Bar, Carlingford Lough   23/10/1838

                                         Description
0  Schooner of Dublin, stranded en route to Cunni...
1  71-ton, 6-year-old schooner. Captain was Darby...
2  Sloop en route from Irvine to Dundalk, struck ...
3  88-ton, 18-year-old iron steamship. Owned by ‘...
4  Schooner valued at £600, became a total wreck,...

C:\Users\spectrum\AppData\Local\Temp\ipykernel_17392\4169143569.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=['Description'], inplace=True)